apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka-service
  name: kafka-service
spec:
  type: NodePort
  selector:
    service: kafka-service
  ports:
    - name: "9092"
      protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30003
    - name: "9093"
      protocol: TCP
      port: 9093
      targetPort: 9093
      nodePort: 30004
    - name: "9094"
      protocol: TCP
      port: 9094
      targetPort: 9094
      nodePort: 30005

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kafka-service
  name: kafka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafka-service
  template:
    metadata:
      labels:
        service: kafka-service
    spec:
      containers:
        - name: kafka
          image: docker.io/bitnami/kafka:latest
          ports:
            - containerPort: 9092
            - containerPort: 9093
            - containerPort: 9094
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami
          env:
            - name: KAFKA_CFG_NODE_ID
              value: "0"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "controller,broker"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "0@kafka-service:9093"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-service:9092,EXTERNAL://kafka-service:9094"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
      volumes:
        - name: kafka-data
          emptyDir: {}
