apiVersion: v1
kind: Service
metadata:
  labels:
    service: locations-grpc-server
  name: locations-grpc-server
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      nodePort: 30003
  selector:
    service: locations-grpc-server
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: locations-grpc-server
  name: locations-grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      service: locations-grpc-server
  template:
    metadata:
      labels:
        service: locations-grpc-server
    spec:
      containers:
        - image: dockerhub4aj/locations-grpc-server:latest
          name: locations-grpc-server
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "64m"
            limits:
              memory: "256Mi"
              cpu: "256m"
      restartPolicy: Always
