apiVersion: v1
kind: Service
metadata:
  labels:
    service: locations-grpc-server
  name: locations-grpc-server
spec:
  ports:
    - name: "5005"
      port: 5005
      targetPort: 5005
      nodePort: 30006
  selector:
    service: locations-grpc-server
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: locations-grpc-server
  name: locations-grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      service: locations-grpc-server
  template:
    metadata:
      labels:
        service: locations-grpc-server
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z -w 2 kafka-service 9094; do sleep 2; done",
            ]
      containers:
        - image: dockerhub4aj/locations-grpc-server:latest
          name: locations-grpc-server
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "64m"
            limits:
              memory: "256Mi"
              cpu: "256m"
      restartPolicy: Always
